<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$settings = WP_AICHAT_Settings::get();
$w = $settings['widget'];
$posts = get_posts( array( 'post_type' => array( 'page', 'post' ), 'post_status' => 'publish', 'posts_per_page' => -1, 'orderby' => 'title', 'order' => 'ASC' ) );
?>
<div class="aichat-admin" data-page="placement">
	<header class="aichat-page-header"><h1><?php esc_html_e( 'Placement', 'wp-aichat' ); ?></h1><p><?php esc_html_e( 'Control where the widget appears and use the shortcode.', 'wp-aichat' ); ?></p></header>
	<form id="aichat-placement-form">
		<section class="aichat-card"><h2><?php esc_html_e( 'Widget Mode', 'wp-aichat' ); ?></h2><div class="aichat-radio-row"><label><input type="radio" name="widget.shortcode_mode" value="0" <?php checked( ! $w['shortcode_mode'] ); ?>><?php esc_html_e( 'Floating Bubble', 'wp-aichat' ); ?></label><label><input type="radio" name="widget.shortcode_mode" value="1" <?php checked( $w['shortcode_mode'] ); ?>><?php esc_html_e( 'Shortcode Only', 'wp-aichat' ); ?></label></div><div data-floating-controls><label><?php esc_html_e( 'Position', 'wp-aichat' ); ?><select name="widget.position"><option value="bottom-right"><?php esc_html_e( 'Bottom Right', 'wp-aichat' ); ?></option><option value="bottom-left"><?php esc_html_e( 'Bottom Left', 'wp-aichat' ); ?></option><option value="bottom-center"><?php esc_html_e( 'Bottom Center', 'wp-aichat' ); ?></option><option value="custom"><?php esc_html_e( 'Custom', 'wp-aichat' ); ?></option></select></label><div class="aichat-grid-2" data-custom-position><label><?php esc_html_e( 'X offset (px)', 'wp-aichat' ); ?><input type="number" name="widget.custom_x" value="<?php echo esc_attr( $w['custom_x'] ); ?>"></label><label><?php esc_html_e( 'Y offset (px)', 'wp-aichat' ); ?><input type="number" name="widget.custom_y" value="<?php echo esc_attr( $w['custom_y'] ); ?>"></label></div></div></section>
		<section class="aichat-card"><h2><?php esc_html_e( 'Shortcode', 'wp-aichat' ); ?></h2><button type="button" class="aichat-code-copy" id="aichat-copy-shortcode">[wp_aichat]</button><p class="aichat-note"><?php esc_html_e( 'When shortcode is placed on a page, the floating bubble is hidden on that page automatically.', 'wp-aichat' ); ?></p></section>
		<section class="aichat-card"><h2><?php esc_html_e( 'Attribution', 'wp-aichat' ); ?></h2><label class="aichat-toggle"><input type="checkbox" name="widget.show_powered_by" <?php checked( $w['show_powered_by'] ); ?>><span></span><?php esc_html_e( 'Show optional Powered by WP AI Chat text', 'wp-aichat' ); ?></label><p class="aichat-note"><?php esc_html_e( 'Attribution is optional and disabled by default.', 'wp-aichat' ); ?></p></section>
		<section class="aichat-card"><h2><?php esc_html_e( 'Visibility', 'wp-aichat' ); ?></h2><label><?php esc_html_e( 'Show on', 'wp-aichat' ); ?><select name="show_on_mode"><option value="all"><?php esc_html_e( 'All pages', 'wp-aichat' ); ?></option><option value="specific"><?php esc_html_e( 'Specific pages', 'wp-aichat' ); ?></option></select></label><label><?php esc_html_e( 'Specific pages/posts', 'wp-aichat' ); ?><select multiple name="show_on_ids"><?php foreach ( $posts as $post ) : ?><option value="<?php echo esc_attr( $post->ID ); ?>" <?php selected( in_array( $post->ID, $settings['show_on_ids'], true ) ); ?>><?php echo esc_html( get_the_title( $post ) ); ?></option><?php endforeach; ?></select></label><label><?php esc_html_e( 'Hide on specific pages/posts', 'wp-aichat' ); ?><select multiple name="hide_on_ids"><?php foreach ( $posts as $post ) : ?><option value="<?php echo esc_attr( $post->ID ); ?>" <?php selected( in_array( $post->ID, $settings['hide_on_ids'], true ) ); ?>><?php echo esc_html( get_the_title( $post ) ); ?></option><?php endforeach; ?></select></label><button class="aichat-button aichat-button-primary" type="submit"><?php esc_html_e( 'Save Placement', 'wp-aichat' ); ?></button><div class="aichat-inline-status" id="aichat-placement-status"></div></section>
	</form>
</div>
