<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$settings = WP_AICHAT_Settings::get();
$w = $settings['widget'];
?>
<div class="aichat-admin" data-page="designer">
	<header class="aichat-page-header"><h1><?php esc_html_e( 'Widget Designer', 'wp-aichat' ); ?></h1><p><?php esc_html_e( 'Design the chat widget and preview changes live.', 'wp-aichat' ); ?></p></header>
	<form id="aichat-widget-form" class="aichat-two-col">
		<div>
			<section class="aichat-card"><h2><?php esc_html_e( 'Identity', 'wp-aichat' ); ?></h2><label><?php esc_html_e( 'Bot name', 'wp-aichat' ); ?><input name="widget.bot_name" value="<?php echo esc_attr( $w['bot_name'] ); ?>"></label><label><?php esc_html_e( 'Bot avatar', 'wp-aichat' ); ?><div class="aichat-upload-row"><input name="widget.bot_avatar_url" value="<?php echo esc_url( $w['bot_avatar_url'] ); ?>"><button type="button" class="aichat-button aichat-button-secondary" data-media-target="widget.bot_avatar_url"><?php esc_html_e( 'Upload', 'wp-aichat' ); ?></button></div></label></section>
			<section class="aichat-card"><h2><?php esc_html_e( 'Bubble', 'wp-aichat' ); ?></h2><label><?php esc_html_e( 'Bubble background color', 'wp-aichat' ); ?><input type="color" name="widget.bubble_color" value="<?php echo esc_attr( $w['bubble_color'] ); ?>"></label><div class="aichat-radio-row"><label><input type="radio" name="widget.bubble_icon" value="default" <?php checked( $w['bubble_icon'], 'default' ); ?>><?php esc_html_e( 'Default', 'wp-aichat' ); ?></label><label><input type="radio" name="widget.bubble_icon" value="custom" <?php checked( $w['bubble_icon'], 'custom' ); ?>><?php esc_html_e( 'Custom Upload', 'wp-aichat' ); ?></label></div><label data-custom-icon><?php esc_html_e( 'Custom icon URL', 'wp-aichat' ); ?><div class="aichat-upload-row"><input name="widget.bubble_icon_url" value="<?php echo esc_url( $w['bubble_icon_url'] ); ?>"><button type="button" class="aichat-button aichat-button-secondary" data-media-target="widget.bubble_icon_url"><?php esc_html_e( 'Upload', 'wp-aichat' ); ?></button></div></label></section>
			<section class="aichat-card"><h2><?php esc_html_e( 'Chat Window', 'wp-aichat' ); ?></h2><div class="aichat-grid-2"><label><?php esc_html_e( 'Width (px)', 'wp-aichat' ); ?><input type="number" name="widget.window_width" value="<?php echo esc_attr( $w['window_width'] ); ?>"></label><label><?php esc_html_e( 'Height (px)', 'wp-aichat' ); ?><input type="number" name="widget.window_height" value="<?php echo esc_attr( $w['window_height'] ); ?>"></label><label><?php esc_html_e( 'Background color', 'wp-aichat' ); ?><input type="color" name="widget.window_bg" value="<?php echo esc_attr( $w['window_bg'] ); ?>"></label><label><?php esc_html_e( 'Border radius (px)', 'wp-aichat' ); ?><input type="number" name="widget.border_radius" value="<?php echo esc_attr( $w['border_radius'] ); ?>"></label></div><label class="aichat-toggle"><input type="checkbox" name="widget.shadow" <?php checked( $w['shadow'] ); ?>><span></span><?php esc_html_e( 'Shadow', 'wp-aichat' ); ?></label></section>
			<section class="aichat-card"><h2><?php esc_html_e( 'Header', 'wp-aichat' ); ?></h2><div class="aichat-grid-2"><label><?php esc_html_e( 'Header background color', 'wp-aichat' ); ?><input type="color" name="widget.header_bg" value="<?php echo esc_attr( $w['header_bg'] ); ?>"></label><label><?php esc_html_e( 'Header text color', 'wp-aichat' ); ?><input type="color" name="widget.header_text_color" value="<?php echo esc_attr( $w['header_text_color'] ); ?>"></label></div></section>
			<section class="aichat-card"><h2><?php esc_html_e( 'Messages', 'wp-aichat' ); ?></h2><div class="aichat-grid-2"><label><?php esc_html_e( 'User message background', 'wp-aichat' ); ?><input type="color" name="widget.user_msg_bg" value="<?php echo esc_attr( $w['user_msg_bg'] ); ?>"></label><label><?php esc_html_e( 'User message text', 'wp-aichat' ); ?><input type="color" name="widget.user_msg_color" value="<?php echo esc_attr( $w['user_msg_color'] ); ?>"></label><label><?php esc_html_e( 'Bot message background', 'wp-aichat' ); ?><input type="color" name="widget.bot_msg_bg" value="<?php echo esc_attr( $w['bot_msg_bg'] ); ?>"></label><label><?php esc_html_e( 'Bot message text', 'wp-aichat' ); ?><input type="color" name="widget.bot_msg_color" value="<?php echo esc_attr( $w['bot_msg_color'] ); ?>"></label><label><?php esc_html_e( 'Font size (px)', 'wp-aichat' ); ?><input type="number" name="widget.font_size" value="<?php echo esc_attr( $w['font_size'] ); ?>"></label><label><?php esc_html_e( 'Font family', 'wp-aichat' ); ?><select name="widget.font_family"><option>inherit</option><option>Inter</option><option>system-ui</option><option>Georgia</option><option>monospace</option></select></label></div></section>
			<section class="aichat-card"><h2><?php esc_html_e( 'Content', 'wp-aichat' ); ?></h2><label><?php esc_html_e( 'Welcome message', 'wp-aichat' ); ?><input name="widget.welcome_message" value="<?php echo esc_attr( $w['welcome_message'] ); ?>"></label><label><?php esc_html_e( 'Input placeholder', 'wp-aichat' ); ?><input name="widget.input_placeholder" value="<?php echo esc_attr( $w['input_placeholder'] ); ?>"></label><button class="aichat-button aichat-button-primary" type="submit"><?php esc_html_e( 'Save Widget', 'wp-aichat' ); ?></button><div class="aichat-inline-status" id="aichat-widget-status"></div></section>
		</div>
		<aside class="aichat-preview-wrap"><div class="aichat-card"><h2><?php esc_html_e( 'Live Preview', 'wp-aichat' ); ?></h2><div id="aichat-widget-preview"></div></div></aside>
	</form>
</div>
